version: '3.8'
services:
  db:
    image: postgres
    container_name: point-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: point_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
